// src/components/avatar.component.ts
import { Component, Input } from '@angular/core';

const fallbackAvatar = '/images/avatar-fallback.png';

@Component({
  selector: 'app-avatar',
  standalone: true,
  template: `
    <img
      [class]="'shrink-0 rounded-full object-cover ' + className"
      [src]="currentSrc"
      [alt]="alt"
      loading="lazy"
      (error)="useFallback()"
    />
  `,
})
export class AvatarComponent {
  @Input() src = fallbackAvatar;
  @Input({ required: true }) alt = '';
  @Input() className = '';

  get currentSrc(): string {
    return this.src || fallbackAvatar;
  }

  useFallback(): void {
    this.src = fallbackAvatar;
  }
}

// src/components/Avatar.tsx
import { useState } from 'react';
import { cn } from '../utils/cn';

type AvatarProps = {
  src?: string;
  alt: string;
  className?: string;
};

const fallbackAvatar = '/images/avatar-fallback.png';

export function Avatar({ src, alt, className }: AvatarProps) {
  const [imageSrc, setImageSrc] = useState(src || fallbackAvatar);

  return (
    <img
      className={cn('shrink-0 rounded-full object-cover', className)}
      src={imageSrc}
      alt={alt}
      loading="lazy"
      onError={() => setImageSrc(fallbackAvatar)}
    />
  );
}
